### PR TITLE
Added solution and md file for GFG POTD (03/03/2024)

### PR DESCRIPTION
**Pull request by SaranshBangar**
Additionaly I have renamed "02-mach.cpp" to "02-march.cpp"

### CODE REVIEW

**Review by getlost01 — COMMENTED** [review]
good

**Comment by getlost01** [comment]
BTW, your solution is giving TLE,
I have made a change to the function. Instead of passing a string, you need to pass its reference so that the comparison will be based on its reference value instead of the copied value because copying a value has its own time and space complexities.

### Slightly updated soln:
```cpp
bool func(string& a, string& b)
{
    return a+b > b+a;
}
class Solution{
public:
	string printLargest(int n, vector<string> &arr)
	{
	    sort(arr.begin(), arr.end(), func);
        string out;
        for (auto s : arr)
            out+=s;
        return out;
	}
};
```

**Comment by getlost01** [comment]
It is best practice to commit your solution in a single commit if the number of file changes is small, as in this repo the changes made are usually small every day. So try to commit all files in one go.

**Comment by SaranshBangar** [comment]
> BTW, your solution is giving TLE, I have made a change to the function. Instead of passing a string, you need to pass its reference so that the comparison will be based on its reference value instead of the copied value because copying a value has its own time and space complexities.
> 
> ### Slightly updated soln:
> ```c++
> bool func(string& a, string& b)
> {
>     return a+b > b+a;
> }
> class Solution{
> public:
> 	string printLargest(int n, vector<string> &arr)
> 	{
> 	    sort(arr.begin(), arr.end(), func);
>         string out;
>         for (auto s : arr)
>             out+=s;
>         return out;
> 	}
> };
> ```

I was not getting any errors that is why I raised this PR, but no worries, I will make sure that this does'nt happen in the future

**Comment by SaranshBangar** [comment]
> It is best practice to commit your solution in a single commit if the number of file changes is small, as in this repo the changes made are usually small every day. So try to commit all files in one go.

I do commit all the files in a single go, should I also change the md file for the main github webpage?

**Comment by getlost01** [comment]
Surely, but all in 1 commit. Because now I have lot of do this result obviously delay in uploading the solutions on repo, and I want there should be a good solution on this repo kinda thing.

**Pull request merged**
